# Generated by Django 5.1.1 on 2024-10-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exoplanet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pl_name', models.CharField(max_length=150)),
                ('hostname', models.CharField(max_length=150)),
                ('gaia_id', models.CharField(max_length=150)),
                ('ra', models.FloatField()),
                ('dec', models.FloatField()),
                ('sy_dist', models.FloatField()),
                ('disc_year', models.IntegerField()),
                ('discoverymethod', models.CharField(max_length=150)),
                ('disc_facility', models.CharField(max_length=150)),
            ],
        ),
    ]
