# Usar una imagen base de Python más completa
FROM python:3.9

# Instalar dependencias del sistema necesarias
RUN apt-get update && apt-get install -y \
    gcc \
    default-libmysqlclient-dev \
    pkg-config \
    && rm -rf /var/lib/apt/lists/*

# Establecer el directorio de trabajo
WORKDIR /app

# Actualizar pip
RUN pip install --upgrade pip

# Copiar el archivo requirements.txt
COPY requirements.txt /app/

# Instalar dependencias de Python
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el resto de los archivos del proyecto
COPY . /app/

# Exponer el puerto en el que se ejecutará Django
EXPOSE 8000

# Comando para iniciar el servidor de desarrollo de Django
CMD python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000
